### ISSUE TITLE
config rot: invoker runtimes registry

### ISSUE THREAD

**Issue by dgrove-oss** [apache/incubator-openwhisk-deploy-kube#360]
The env vars related to overriding the docker pulls for the invoker have gotten out of synch with upstream.  Need to update to something like.

```
            - name: "CONFIG_whisk_runtimes_defaultImagePrefix"
              valueFrom:
                configMapKeyRef:
                  name: whisk.runtimes
                  key: runtimes_default_image_prefix
            - name: "CONFIG_whisk_runtimes_defaultImageTag"
              valueFrom:
                configMapKeyRef:
                  name: whisk.runtimes
                  key: runtimes_default_image_tag
            - name: "CONFIG_whisk_runtimes_bypassPullForLocalImages"
              valueFrom:
                configMapKeyRef:
                  name: whisk.runtimes
                  key: runtimes_bypass_pull_for_local_images
            - name: "CONFIG_whisk_runtimes_localImagePrefix"
              valueFrom:
                configMapKeyRef:
                  name: whisk.runtimes
                  key: runtimes_local_image_prefix
```
