### ISSUE TITLE
error in documenting providers database

### ISSUE THREAD

**Issue by sciabarracom** [apache/incubator-openwhisk-deploy-kube#407]
it is NOT

```
providers:
   alarm:
     enable: true
     db:
       ....
```

but

```
providers:
  db:
    ...
  alarm:
    enabled: true
```
For deploying with an external ingress you need

```
ingress:
   type: Standard
   domain: ingress.public.domain
   apiHostName: ingress.public.domain
```

it is not clearly documented (I had to read the code)
