### ISSUE TITLE
Cannot change internal keys

### ISSUE THREAD

**Issue by sciabarracom** [apache/incubator-openwhisk-deploy-kube#418]
If I try to change authorization keys, for example those:

```
whisk:
  ingress:
     type: Standard
     domain: sciabarra.cloud
     apiHostName: sciabarra.cloud
     apiHostPort: 443
  auth:
    system: "965279e9-cdaf-4e1e-8a2f-5f49da805e4d:AVmLjhb3jlgPmBh69l0jt2Gn871Rqx79uNeDp8mM1d7tgwUkX1HanK7Msq0OVL5e"
    guest: "965279e9-cdaf-4e1e-8a2f-5f49da805e4d:AVmLjhb3jlgPmBh69l0jt2Gn871Rqx79uNeDp8mM1d7tgwUkX1HanK7Msq0OVL5e"
```

When I deploy with helm and I check the status with kubectl, I get multiple Error for the `install-packages-xxx` and I cannot set the key with `wsk property set`.

If I leave the default values, removing whisk.auth.* everything works fine.
